import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { decodePng, inkBounds } from './helpers/png';

/**
 * The sprite frames the game actually ships.
 *
 * These are generated by tools/sprites/slice-swing-sheet.mjs, and the thing that
 * goes wrong with a slicer is that it cuts through the artwork. It did: the
 * putter sheet's rows are not the same height, and splitting it down the middle
 * took the bottom off her shoes, which showed up in play as a missing foot at
 * address on the green. Checking the shipped PNGs catches that whoever re-cuts
 * the sheets and whatever they cut them with.
 */
const FRAME_FILES = [
  'frame-00-address-1.png',
  'frame-01-address-2-wiggle.png',
  'frame-02-backswing-top.png',
  'frame-03-downswing-impact.png',
  'frame-04-follow-through.png'
];

const SETS = ['driver', 'iron', 'putter'];

function loadFrame(set: string, file: string) {
  const path = fileURLToPath(new URL(`../public/assets/sprites/${set}/${file}`, import.meta.url));
  return decodePng(readFileSync(path));
}

describe.each(SETS)('%s swing frames', (set) => {
  const frames = FRAME_FILES.map((file) => ({ file, image: loadFrame(set, file) }));

  it('draws every pose on one canvas, so swapping frames does not resize her', () => {
    const sizes = new Set(frames.map(({ image }) => `${image.width}x${image.height}`));
    expect([...sizes]).toHaveLength(1);
  });

  it.each(frames)('keeps $file clear of the frame edge, so nothing is cut off', ({ image }) => {
    const bounds = inkBounds(image);
    expect(bounds).not.toBeNull();

    // The slicer leaves a few pixels of margin. Ink running into the edge means
    // the crop went through the figure — a shoe, a clubhead, the top of her cap.
    expect(bounds!.minX).toBeGreaterThan(0);
    expect(bounds!.minY).toBeGreaterThan(0);
    expect(bounds!.maxX).toBeLessThan(image.width - 1);
    expect(bounds!.maxY).toBeLessThan(image.height - 1);
  });

  it('stands her on one baseline across the swing', () => {
    // She is on her feet at address and through impact. The follow-through comes
    // up onto a toe, so only the poses that are flat-footed are compared.
    const flatFooted = [0, 1, 3].map((index) => inkBounds(frames[index].image)!.maxY);
    const spread = Math.max(...flatFooted) - Math.min(...flatFooted);
    const height = frames[0].image.height;

    expect(spread / height).toBeLessThan(0.06);
  });
});
